### ISSUE TITLE
Write to sd card can’t boot loader.

### ISSUE THREAD

**Issue by thomasbergersen** [inindev/rock-5b#11]

**Comment by thomasbergersen** [comment]
My rock5 model is v1.42,Please update the  img file . Thank you sir

**Comment by inindev** [comment]
**The latest u-boot**
https://github.com/inindev/uboot-rockchip/releases/tag/v2024.07

**The latest kernel**
https://github.com/inindev/linux-rockchip/releases/tag/v6.10.0-rc6

**The latest complete image with u-boot and kernel**
https://github.com/inindev/debian-image/releases/tag/v12.6

**For the Rock-5b**
```
wget https://github.com/inindev/debian-image/releases/download/v12.6/rock-5b_bookworm-12.6.img.xz
sudo su
xzcat rock-5b_bookworm-12.6.img.xz > /dev/sd<your mmc device>
```

**Comment by thomasbergersen** [comment]
> **The latest u-boot** https://github.com/inindev/uboot-rockchip/releases/tag/v2024.07
> 
> **The latest kernel** https://github.com/inindev/linux-rockchip/releases/tag/v6.10.0-rc6
> 
> **The latest complete image with u-boot and kernel** https://github.com/inindev/debian-image/releases/tag/v12.6
> 
> **For the Rock-5b**
> 
> ```
> wget https://github.com/inindev/debian-image/releases/download/v12.6/rock-5b_bookworm-12.6.img.xz
> sudo su
> xzcat rock-5b_bookworm-12.6.img.xz > /dev/sd<your mmc device>
> ```

There are no startup issues with these image files.

Thank you for the excellent work you have done.
