### ISSUE TITLE
Cannot build / compile Debian Bookworm

### ISSUE THREAD

**Issue by luckylinux** [inindev/rock-5b#2]
I successfully managed to build Debian Bookworm & Debian Kernel, as well as DTB and U-Boot.

I had to change the scripts to use gcc-12, as I was using the Rock 5B itself from Radxa Image (upgraded to Debian Bookworm) to do the build. I also updated linux-firmware version and tried latest kernel 6.6-rc7 as well as 6.5.9, a bit more recent than what the script originally downloads.

Maybe you could do a version bump :+1: .

The problem is that while there are no errors reported during the build process and the IMG file is correctly generated & written to the SD card, it just does NOT boot ! The blue/green LED alternated blinking, typical of a normal boot, does not happen. Instead, only the green LED stays permanently lit.

Do you have an idea of what might be causing this ?

Possibly the script is not taking the required DTB files & copying them to the boot partition ?

**Comment by luckylinux** [comment]
Just tried your Debian Bookworm image. It also does NOT boot. 

I tried your latest Debian Trixie image and that booted without issues.

If so, is Debian Bookworm known to NOT work correctly ?

**Comment by inindev** [comment]
I have published a bookworm release based on the latest 6.6 kernel: https://github.com/inindev/rock-5b/releases/tag/v12-6.6

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


$ uname -a
Linux rock5b-arm64 6.6.0-1-arm64 #1 SMP PREEMPT Debian 6.6.0-1 (2023-10-30) aarch64 GNU/Linux
```

Are you sure you used ```xzcat``` to write it to sd?
```
sudo su
xzcat rock-5b_bookworm-v12-6.6.img.xz > /dev/sdX
```

**Comment by luckylinux** [comment]
> I have published a bookworm release based on the latest 6.6 kernel: https://github.com/inindev/rock-5b/releases/tag/v12-6.6
> 
> ```
> $ cat /etc/os-release
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> 
> 
> $ uname -a
> Linux rock5b-arm64 6.6.0-1-arm64 #1 SMP PREEMPT Debian 6.6.0-1 (2023-10-30) aarch64 GNU/Linux
> ```
> 
> Are you sure you used `xzcat` to write it to sd?
> 
> ```
> sudo su
> xzcat rock-5b_bookworm-v12-6.6.img.xz > /dev/sdX
> sync
> ```

I am pretty sure I used xzcat, same as for Debian Trixie.

Did you include the Docker/Podman options that I mentioned in the kernel .Config?

Could you also upload the Kernel images + headers + libc ? I cannot really re-install everything from scratch. I also had to spend a few days configuring Podman and cannot exactly remember all the little things I had to tweak :(.

**Comment by inindev** [comment]
I only responded to the issue you opened here.  Can you open a new issue with a title like: "feature request: support xyz" then provide information on why its useful and where I can learn more about it?  I want to make it easy for anyone who searches for a result can find it.

**Comment by luckylinux** [comment]
Sure. I guess we should have "split" a while ago the topics. I just mentioned it here since Docker was also mentioned in the first post. But there are a lot of inputs in this discussion already ... 

Never mind. I'll try to create another topic. But I guess if I can't get Podman/Docker to work on this damn ARM SBC I'll just have to stick with some Standard AMD64 Hardware (possibly in a VM). These SBC have 1000 issues all the time unfortunately :(. Tried many ARM SBC over the years and whether it's Mainline Support, Lack of Documentation, lack of Software Support, etc, there is always something unfortunately.
