### ISSUE TITLE
No audio output although /dev/snd is available

### ISSUE THREAD

**Issue by Rastafabisch** [inindev/rock-5b#7]
I installed `shairport-sync` via docker. However there was not any output to the headphone jack. I tried adjusting the `alsamixer` as well as directly playing a wav audio file on the rock directly using `aplay -vv some.wav`, which doesn't through an any errors but neither outputs anything to the headphone jack.

[This](https://github.com/Joshua-Riek/ubuntu-rockchip/issues/291) might be related?

EDIT:
I installed `alsa-utils` beforehand

**Comment by Rastafabisch** [comment]
Yes. The mentioned issue is related indeed. Running its provided also setup script enables audio on my rock.

Feel free to close the issue.

**Comment by inindev** [comment]
closing issue
